work on pipeline

diff --git a/.github/workflows/main-pipeline.yml b/.github/workflows/main-pipeline.yml
--- a/.github/workflows/main-pipeline.yml
+++ b/.github/workflows/main-pipeline.yml
@@ -14,24 +14,24 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v3  # Action for checkout repository code
 
-      - name: Setup Node.js
-        uses: actions/setup-node@v3
-        with:
-          node-version: '20'  # Node.js version 20
+     #   - name: Setup Node.js
+     #     uses: actions/setup-node@v3
+     #     with:
+     #       node-version: '20'  # Node.js version 20
 
-      - name: Install dependencies
-        run: npm install      # Install Node.js dependencies
+     #   - name: Install dependencies
+     #     run: npm install      # Install Node.js dependencies
 
-      - name: Run tests and capture results
-        run: |
-          mkdir -p test-results
-          npm test > test-results/results.txt # Remove '|| true' to fail on test failure
+     #   - name: Run tests and capture results
+     #     run: |
+      #      mkdir -p test-results
+      #      npm test > test-results/results.txt # Remove '|| true' to fail on test failure
 
-      - name: Upload test results
-        uses: actions/upload-artifact@v3
-        with:
-          name: test-results
-          path: test-results/results.txt
+      #  - name: Upload test results
+      #    uses: actions/upload-artifact@v3
+     #     with:
+      #      name: test-results
+      #      path: test-results/results.txt
 
   deploy:
     name: Deploy to Self-Hosted Runner
@@ -42,21 +42,21 @@ jobs:
         uses: actions/checkout@v3
 
       # download test results 
-       - name: Download test results
-         uses: actions/download-artifact@v3
-         with:
-           name: test-results
+     #    - name: Download test results
+     #      uses: actions/download-artifact@v3
+      #     with:
+      #       name: test-results
 
       # show test results 
-       - name: Show test results
-         run: cat test-results/results.txt
+       #  - name: Show test results
+        #   run: cat test-results/results.txt
 
-      - name: Install production dependencies
-        run: npm install --omit=dev # Install only production dependencies
+       # - name: Install production dependencies
+       #   run: npm install --omit=dev # Install only production dependencies
 
 
-      - name: Stop previous application
-        run: pm2 delete app || true
+       # - name: Stop previous application
+       #   run: pm2 delete app || true
 
-      - name: Start application with pm2
-        run: pm2 start index.js --name app
+       # - name: Start application with pm2
+       #   run: pm2 start index.js --name app
